### ISSUE TITLE
Fix documentation CI failure

### ISSUE THREAD

**Issue by thewtex** [InsightSoftwareConsortium/ITKSphinxExamples#324] opened 2022-03-08 20:07 UTC

**Comment by tbirdso** [comment] 2022-03-08 22:29
After updating input/output data directories for [`KeepRegionsAboveLevel`](https://github.com/InsightSoftwareConsortium/ITKSphinxExamples/tree/master/src/Filtering/LabelMap/KeepRegionsAboveLevel) on `data.kitware.com` everything except documentation is passing 🤷‍♂️ 

Updating the issue title to reflect remaining work.

**Comment by tbirdso** [comment] 2022-03-09 14:39
In contrast to CDash reporting, CI logs show that failure occurs at the Doxygen build step:
```
2022-03-08T22:09:10.9217174Z [1585/1593] Generating sphinx documentation: html
2022-03-08T22:09:10.9217505Z FAILED: CMakeFiles/build_html 
2022-03-08T22:09:10.9218286Z cd /home/runner/work/bld/ITKEx-build && /home/runner/work/bld/itkpython/bin/sphinx-build -b html -c /home/runner/work/bld/ITKEx-build/Formatting /home/runner/work/bld/ITKEx-build /home/runner/work/bld/ITKEx-build/html
2022-03-08T22:09:10.9218407Z Running Sphinx v4.4.0
2022-03-08T22:09:10.9218418Z 
2022-03-08T22:09:10.9218571Z Extension error (doxylink.doxylink):
2022-03-08T22:09:10.9219106Z Handler <function setup_doxylink_roles at 0x7fe8b838fdc0> for event 'builder-inited' threw an exception (exception: no element found: line 1, column 0)
2022-03-08T22:09:10.9222461Z [1586/1593] Building CXX object src/Segmentation/ConnectedComponents/LabelConnectComponentsInGrayscaleImage/CMakeFiles/LabelConnectComponentsInGrayscaleImage.dir/Code.cxx.o
2022-03-08T22:09:10.9222939Z [1587/1593] Building CXX object src/Segmentation/ConnectedComponents/ExtraLargestConnectComponentFromBinaryImage/CMakeFiles/ExtraLargestConnectComponentFromBinaryImage.dir/Code.cxx.o
2022-03-08T22:09:10.9223085Z ninja: build stopped: subcommand failed.
2022-03-08T22:09:10.9223222Z ninja: build stopped: subcommand failed.
2022-03-08T22:09:10.9223342Z Command exited with the value: 1
```

I am able to recreate this failure locally, will continue to investigate.

**Comment by tbirdso** [comment] 2022-03-09 16:48
From tracing through the doxylink error, it looks like CMake is trying to fetch an archive from `public.kitware.com` which no longer exists:

[DownloadDoxygenTAG.CMake](https://github.com/InsightSoftwareConsortium/ITKSphinxExamples/blob/master/CMake/DownloadDoxygenTAG.cmake)

References broken link: [https://public.kitware.com/pub/itk/NightlyDoxygen/InsightDoxygenDocTag.gz](https://public.kitware.com/pub/itk/NightlyDoxygen/InsightDoxygenDocTag.gz)

@thewtex could you please verify whether `InsightDoxygenDocTag-5.2.0.gz` at [https://data.kitware.com/#item/60674d8a2fa25629b94769d2](https://data.kitware.com/#item/60674d8a2fa25629b94769d2) is the correct archive to use?

**Comment by tbirdso** [comment] 2022-03-09 17:18
Note that both [https://itk.org/files/NightlyDoxygen/InsightDoxygenDocTag.gz](https://itk.org/files/NightlyDoxygen/InsightDoxygenDocTag.gz) and [data.kitware.com/.../InsightDoxygenDocTag-5.2.0.gz](https://data.kitware.com/#folder/60674c432fa25629b94768fd) appear to be valid archives allowing docs to build successfully. Awaiting word on the appropriate archive to fetch.

**Comment by dzenanz** [comment] 2022-03-09 18:54
The first one is the right one.

**Comment by tbirdso** [comment] 2022-03-10 17:13
[50 CDash warnings](https://open.cdash.org/viewBuildError.php?type=1&buildid=7718766) are remaining in regards to duplicate linkage at `breathelink` tags:

>[ITKEx-build/src/Bridge/VtkGlue/ConvertAnitkImageTovtkImageData/Documentation.rst:131](https://github.com/InsightSoftwareConsortium/ITK/blob/master/ITKEx-build/src/Bridge/VtkGlue/ConvertAnitkImageTovtkImageData/Documentation.rst#L131): WARNING: Duplicate C++ declaration, also defined at src/Bridge/VtkGlue/ConvertAnRGBitkImageTovtkImageData/Documentation:129.
...

Each warning points to a `:: breathelink` entry in a `.rst` file where other `.rst` files also have `:: breathelink` entry for the same class.

@thewtex Perhaps you could weigh in on whether you think this is an issue in [https://github.com/thewtex/breathelink](https://github.com/thewtex/breathelink)? From what I can tell so far the `no-link` option is intended to address this case so that duplicate declarations are not linked, but it looks like the option is being set correctly in `breathelink.py`.

**Comment by thewtex** [comment] 2022-03-10 18:52
@tbirdso perhaps `breathelink` can be improved? Yes, the intention is to have multiple descriptions of the relevant classes in each example where relevant for quick reference. Maybe these warnings are the result of updating Sphinx.

**Comment by tbirdso** [comment] 2022-03-11 13:56
> Maybe these warnings are the result of updating Sphinx.

This is very possible. The first instance of this warning that I can find is from [February 2nd](https://open.cdash.org/viewBuildError.php?type=1&buildid=7717038), while Sphinx was updated from 3.0.4 to 4.4.0 in [https://github.com/InsightSoftwareConsortium/ITKSphinxExamples/commit/7c77f7953275581dcf11386995aac99c314ee5f2](https://github.com/InsightSoftwareConsortium/ITKSphinxExamples/commit/7c77f7953275581dcf11386995aac99c314ee5f2) on January 27th. It looks like we haven't had a successful docs build since summer 2021.

I will try downgrading Sphinx locally and building.

**Comment by tbirdso** [comment] 2022-03-11 16:16
Relevant discussion in [breathe issue 378](https://github.com/michaeljones/breathe/issues/378) indicates that the `no-link` option for cpp classes is nonfunctional and the related `noindex` option was actually removed from Sphinx in [https://github.com/sphinx-doc/sphinx/pull/7895](https://github.com/sphinx-doc/sphinx/pull/7895). It seems that `cpp:alias` may be the correct directive to use here as per [https://github.com/sphinx-doc/sphinx/pull/5901](https://github.com/sphinx-doc/sphinx/pull/5901). I will investigate how this could be supported with `breathelink`.

**Comment by tbirdso** [comment] 2022-03-11 19:02
@thewtex @dzenanz  Note that the remaining warnings are about the behind-the-scenes docs structure and should not block the release of documentation as it is currently doing in CI. Is there a CMake/CTest/Github Actions flag that we can use to allow docs CI to ignore warnings (but not errors) and proceed with publishing? Have been unsuccessful in my search for suppressing warnings so far.

**Comment by tbirdso** [comment] 2022-03-11 19:48
Note that it looks like this is a duplicate of #266 , with a slightly updated warning message via the Sphinx update to v4.4.0. As the scope of this issue (#324) has changed a couple of times I think it will be best to consolidate discussion in #266. Closing #324 as a duplicate.

**Closed by tbirdso** 2022-03-11 19:48 UTC
